[parity]
chain = "/home/parity/spec.json"
base_path = "/tmp/parity/auth2"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8452
[account]
password = ["/home/parity/.local/share/io.parity.ethereum/nodes/docker/auth2/node.pwd"]
[mining]
engine_signer = "0x000bcd493c3674f754335ae9fed13f206a716cde"
reseal_on_txs = "none"