[parity]
chain = "/home/parity/spec.json"
base_path = "/tmp/parity/auth1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8451
[account]
password = ["/home/parity/node.pwd"]
[mining]
engine_signer = "0x0019dd4a8857af4969971a352f7b5bdd1fc5f6c0"
reseal_on_txs = "none"
